# build docker files with the gsplines installed
name: compilation
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - tag: "18.04"
          - tag: "20.04"
          - tag: "22.04"
    steps:
      - name: checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push rafa606/ubuntu-gsplines:${{ matrix.docker_image.tag }}
        uses: docker/build-push-action@v3
        with:
          tags: rafa606/ubuntu-gsplines:${{ matrix.docker_image.tag }}
          file: docker/docker.dockerfile
          push: true
          build-args: |
            BASEIMAGE=rafa606/ubuntu:${{ matrix.docker_image.tag }}
