name: compilation
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: /workdir
    container:
      image: rafa606/cpp-vim
      volumes:
        - ${{ github.workspace }}:/workdir
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Git Sumbodule Update ad build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cpack -G DEB

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/gsplines-0.0.1-amd64.deb
          asset_name: gsplines-0.0.1-amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: "Debian pack"
