name: compilation
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "docker/noetic.dockerfile"
            image_name: "rafa606/vim-ros-noetic-gsplines"
          - file_name: "docker/melodic.dockerfile"
            image_name: "rafa606/vim-ros-melodic-gsplines"
          - file_name: "docker/galactic.dockerfile"
            image_name: "rafa606/vim-ros-galactic-gsplines"
          - file_name: "docker/cpp.dockerfile"
            image_name: "rafa606/cpp-vim-gsplines"
          - file_name: "docker/ubuntu22.04.dockerfile"
            image_name: "rafa606/gsplines:ubuntu22.04"
    steps:
      - name: checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v17.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push ${{ matrix.docker_image.image_name }}
        uses: docker/build-push-action@v2
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
